public with sharing class HelloWorld {
    public void say() {
        System.debug('Hello World');
        System.debug('Hello World 2');
        System.debug('hello world 3 tetsing CLI');
        System.debug('hello world 3 tetsing CLI 2!!');

        
        Integer a = 1;
        if (true) {
            a += 1;
        }
    }

    public void say2() {
        System.debug('Hello World');
        System.debug('Hello World');
    }
}